### ISSUE TITLE
API eingestellt?

### ISSUE THREAD

**Issue by Voltfest** [neandertaler19/MMM-AC-aseag#2]
Hi,

Leider kriege ich keine Abfahrtszeiten mehr angezeigt und der link im vorherigen issue zur Abfrage der stop id funktioniert auch nicht mehr. Wurde die API eingestellt? Die letzten Infos im web sind von 2017 🤔

Ansonsten Super add on für den Spiegel, hab es gerne genutzt. Danke dir schonmal :)

Grüße Voltfest

**Comment by joshua-martius** [comment]
Hi,

hast du eine Lösung für das Problem gefunden?

Ich glaube mittlerweile ist die API vom AVV nur auf Antrag verwendbar (siehe https://avv.de/de/fahrplaene/opendata-service).

**Comment by j-hiller** [comment]
Hi,

ja, es scheint so, als ob es die API in der Form nicht mehr gibt. 
Die Hoffnung wäre, dass sich die "neue" API der AVV ähnlich verhält wie die Alte der ASEAG und man nur die Authentifizierung einbauen muss.
Allerdings habe ich gerade leider nicht die Zeit, mir das im Detail anzuschauen. Zumindest was man so spontan im Netzwerkverkehr von https://auskunft.avv.de sieht, verwenden die eine andere API.

**Comment by Voltfest** [comment]
Schade,
das Modul war echt cool, danke erstmal für Deine Mühe bis hierhin. Ich bin leider echt unerfahren im Coden und mit Git, vielleicht finde ich irgendwann mal die Zeit mir das anzuschauen. Wir halten uns auf dem Laufenden :)
Grüße

**Comment by joshua-martius** [comment]
Ich habe jetzt Zugriff auf die neue API erhalten und werde meine Ergebnisse veröffentlichen sobald das Ganze lauffähig ist.

**Comment by OlJohnny** [comment]
> Ich habe jetzt Zugriff auf die neue API erhalten und werde meine Ergebnisse veröffentlichen sobald das Ganze lauffähig ist.

Schon was weiteres rausgefunden? :D

**Comment by joshua-martius** [comment]
Ja, das ganze funktioniert auch für mich. An dem Projekt hängt nun aber mein privater Access Key den ich natürlich nicht veröffentlichen möchte. Ich könnte das entkoppeln und dann veröffentlichen. Jedoch müsste jeder Nutzer selbst einen Antrag bei der AVV stellen um dann einen Access Key zu erhalten...

**Comment by Voltfest** [comment]
Cool! Das ist ja bei anderen APIs auch nicht unüblich...

**Comment by OlJohnny** [comment]
> Ja, das ganze funktioniert auch für mich. An dem Projekt hängt nun aber mein privater Access Key den ich natürlich nicht veröffentlichen möchte. Ich könnte das entkoppeln und dann veröffentlichen. Jedoch müsste jeder Nutzer selbst einen Antrag bei der AVV stellen um dann einen Access Key zu erhalten...

Cool!
Wenn du das ohne deinen privaten Access Key veröffentlich kannst, wäre ich dir sehr dankbar :D
Einen Antrag bei der AVV zu stellen ist denke ich mal kein sooo großer aufwand für die meisten Bastler hier.

**Comment by joshua-martius** [comment]
Hallo,

habe mir das für dieses Wochenende vorgenommen, werde dann ggf. nen PR machen. :)

**Comment by joshua-martius** [comment]
Here we go:

https://github.com/j-hiller/MMM-AC-aseag/pull/3

Mein erster PR für ein fremdes Projekt :D Hoffe dass der Funktionsumfang ausreicht...
